/*
 * Copyright (C) 2013 Jairo Lopez <jairo.lopez00@gmail.com>
 * California State University Long Beach (CSULB) ALL RIGHTS RESERVED
 */
package rest.config;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author Jairo Lopez <jairo.lopez00@gmail.com>
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(service.ImageFacadeREST.class);
        resources.add(service.GroupsFacadeREST.class);
        resources.add(service.ProfessionalInfoFacadeREST.class);
        resources.add(service.RecipeFacadeREST.class);
        resources.add(service.UsersFacadeREST.class);
        resources.add(service.SecurityGroupFacadeREST.class);
        try {
            Class<?> jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return resources;
    }
    
}
